//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCheck3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMSDataAccessEntities : DbContext
    {
        public EMSDataAccessEntities()
            : base("name=EMSDataAccessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAccess_Group> tbAccess_Group { get; set; }
        public virtual DbSet<tbAccess_GroupMembership> tbAccess_GroupMembership { get; set; }
        public virtual DbSet<tbAccess_GroupRole> tbAccess_GroupRole { get; set; }
    
        public virtual ObjectResult<spAccess_Group_ListGroupsByCompanyID_Result> spAccess_Group_ListGroupsByCompanyID(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAccess_Group_ListGroupsByCompanyID_Result>("spAccess_Group_ListGroupsByCompanyID", companyIDParameter);
        }
    
        public virtual int spAccess_GroupRole_CopyRolesFromUser(Nullable<int> groupID, string userID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAccess_GroupRole_CopyRolesFromUser", groupIDParameter, userIDParameter);
        }
    }
}
