//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCheck3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAccess_GroupMembership
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public string UserID { get; set; }
    
        public virtual tbAccess_Group tbAccess_Group { get; set; }
    }
}
