//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCheck3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompany_CompanyModule
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int ModuleID { get; set; }
        public decimal ModulePrice { get; set; }
    
        public virtual tbCompany_Company tbCompany_Company { get; set; }
        public virtual tbSysReference_Module tbSysReference_Module { get; set; }
    }
}
